FROM ubuntu:16.04
MAINTAINER Kent Knox <kent.knox@amd>

ARG build_type=Release
ARG user_uid

# Install Packages
    # curl -sL https://bazel.build/bazel-release.pub.gpg | apt-key add - && \
    # echo 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8' | tee /etc/apt/sources.list.d/bazel.list && \
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y curl ca-certificates software-properties-common && \
    echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
    add-apt-repository -y ppa:webupd8team/java && \
    curl -sL http://packages.amd.com/rocm/apt/debian/rocm.gpg.key | apt-key add - && \
    echo 'deb [arch=amd64] http://packages.amd.com/rocm/apt/debian/ xenial main' | tee /etc/apt/sources.list.d/rocm.list && \
    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    sudo \
    file \
    build-essential \
    git \
    cmake \
    python-dev \
    python-numpy \
    python-setuptools \
    python-wheel \
    swig \
    rsync \
    libcurl4-openssl-dev \
    oracle-java8-installer \
    pkg-config \
    zip \
    zlib1g-dev \
    unzip \
    bash-completion \
    libopenblas-dev \
    rocm-dev \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Remember other packages for later
#     default-jdk \
#     bazel \

# docker pipeline runs containers with uid 1000
# create a jenkins user with this specific uid so it can use sudo priviledges
# Grant any member of sudo group password-less sudo privileges
RUN useradd --create-home -u ${user_uid} -G sudo --shell /bin/bash jenkins && \
    echo '%sudo   ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/sudo-nopasswd && \
    curl -sL https://github.com/bazelbuild/bazel/releases/download/0.3.1/bazel_0.3.1-linux-x86_64.deb -o bazel.deb && \
    dpkg -i bazel.deb && rm bazel.deb
